Repository SpiNNakerManchester/SpiNNMachine, pull requests merged in 2021-02, with the labels that each got.

#149 Increase test coverage and a few little fixes
  spinn_machine/chip.py
  spinn_machine/ignores/ignore_link.py
  spinn_machine/json_machine.py
  spinn_machine/machine.py
  spinn_machine/multicast_routing_entry.py
  unittests/tag_tests/test_iptag.py
  unittests/test_chip.py
  unittests/test_coresubset.py
  unittests/test_json_machine.py
  unittests/test_link_data.py
  unittests/test_machine.py
  unittests/test_multicast_routing_entry.py
  unittests/test_router.py
  unittests/test_virtual_machine.py
Labels: enhancement

#150 Remove Python 2.7 support
  .github/workflows/python_actions.yml
  doc/source/conf.py
  requirements-test.txt
  requirements.txt
  setup.py
  spinn_machine/chip.py
  spinn_machine/core_subset.py
  spinn_machine/core_subsets.py
  spinn_machine/exceptions.py
  spinn_machine/full_wrap_machine.py
  spinn_machine/horizontal_wrap_machine.py
  spinn_machine/link_data_objects/fpga_link_data.py
  spinn_machine/link_data_objects/spinnaker_link_data.py
  spinn_machine/machine.py
  spinn_machine/no_wrap_machine.py
  spinn_machine/router.py
  spinn_machine/tags/iptag.py
  spinn_machine/tags/reverse_iptag.py
  spinn_machine/vertical_wrap_machine.py
  spinn_machine/virtual_machine.py
  unittests/tag_tests/test_iptag.py
  unittests/tag_tests/test_reverse_iptag.py
Labels: bug, enhancement

#151 added 3.9 and rat 3.8
  .github/workflows/python_actions.yml
  doc/source/conf.py
  setup.py
Labels: enhancement, minor

#153 It really helps a lot if you USE THE RIGHT URL
  doc/doc_requirements.txt
Labels: bug

#154 Split out the list of files to put in documentation
  doc/source/conf.py
  doc/unfiltered-files.txt
Labels: enhancement, minor
