Repository SpiNNakerManchester/SpiNNMachine, pull requests merged in 2021-03, with the labels that each got.

#156 ask the machine for an unused xy
  spinn_machine/machine.py
  unittests/test_virtual_machine.py
Labels: enhancement

#155 by_ethernet now excludes virtual chips
  spinn_machine/full_wrap_machine.py
  spinn_machine/horizontal_wrap_machine.py
  spinn_machine/json_machine.py
  spinn_machine/machine.py
  spinn_machine/no_wrap_machine.py
  spinn_machine/vertical_wrap_machine.py
Labels: bug

#157 Use right token for coveralls
  .github/workflows/python_actions.yml
Labels: bug, minor
